CREATE TABLE IF NOT EXISTS clothing_product (
    product_code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    size TEXT NOT NULL,
    color TEXT NOT NULL,
    price NUMERIC(14, 2) NOT NULL,
    stock_quantity INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS shop_product (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    group_name TEXT NOT NULL,
    segment TEXT NOT NULL,
    size TEXT NOT NULL,
    color TEXT NOT NULL,
    price NUMERIC(14, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code TEXT NOT NULL UNIQUE,
    role_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    username TEXT PRIMARY KEY,
    full_name TEXT NOT NULL,
    password TEXT NOT NULL,
    role_id SMALLINT NOT NULL REFERENCES roles(id),
    age INTEGER,
    gender TEXT,
    email TEXT UNIQUE,
    phone TEXT UNIQUE,
    base_address TEXT,
    default_address_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (age IS NULL OR (age >= 1 AND age <= 120))
);

CREATE TABLE IF NOT EXISTS user_shipping_address (
    address_id TEXT PRIMARY KEY,
    username TEXT NOT NULL REFERENCES users(username) ON DELETE CASCADE,
    recipient_name TEXT NOT NULL,
    recipient_phone TEXT NOT NULL,
    shipping_address TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
    order_id TEXT PRIMARY KEY,
    username TEXT NOT NULL REFERENCES users(username) ON DELETE RESTRICT,
    customer_name TEXT NOT NULL,
    shipping_address TEXT NOT NULL,
    status TEXT NOT NULL,
    total NUMERIC(14, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (status IN ('CHO_XAC_NHAN', 'DA_XAC_NHAN', 'DANG_GIAO', 'DA_GIAO', 'DA_HUY', 'DA_TRA_HANG')),
    CHECK (total >= 0)
);

CREATE TABLE IF NOT EXISTS order_items (
    order_id TEXT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES shop_product(id) ON DELETE RESTRICT,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(14, 2) NOT NULL,
    line_total NUMERIC(14, 2) NOT NULL,
    PRIMARY KEY (order_id, product_id),
    CHECK (quantity > 0),
    CHECK (unit_price >= 0),
    CHECK (line_total >= 0)
);

CREATE TABLE IF NOT EXISTS contact_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL REFERENCES users(username) ON DELETE RESTRICT,
    full_name TEXT NOT NULL,
    topic TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cart_items (
    username TEXT NOT NULL REFERENCES users(username) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES shop_product(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (username, product_id),
    CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_user_shipping_address_username
    ON user_shipping_address(username);

CREATE INDEX IF NOT EXISTS idx_orders_username
    ON orders(username);

CREATE INDEX IF NOT EXISTS idx_order_items_product_id
    ON order_items(product_id);

CREATE INDEX IF NOT EXISTS idx_contact_requests_username
    ON contact_requests(username);

CREATE INDEX IF NOT EXISTS idx_contact_requests_created_at
    ON contact_requests(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_cart_items_username
    ON cart_items(username);

INSERT INTO roles (role_code, role_name)
VALUES ('ADMIN', 'Administrator'), ('CUSTOMER', 'Customer')
ON CONFLICT (role_code) DO NOTHING;

INSERT INTO users (username, full_name, password, role_id)
SELECT 'admin', 'Quản trị viên', 'admin123', id
FROM roles
WHERE role_code = 'ADMIN'
ON CONFLICT (username) DO NOTHING;

INSERT INTO users (username, full_name, password, role_id)
SELECT 'demo', 'Khách Demo', '123456', id
FROM roles
WHERE role_code = 'CUSTOMER'
ON CONFLICT (username) DO NOTHING;

WITH group_defs AS (
    SELECT *
    FROM (
        VALUES
            ('AD-M', 'Người lớn', 'Nam', 1,
             ARRAY['Áo thun nam', 'Áo sơ mi nam', 'Quần jean nam', 'Quần kaki nam', 'Áo polo nam', 'Áo khoác nam']::TEXT[]),
            ('AD-F', 'Người lớn', 'Nữ', 19,
             ARRAY['Áo thun nữ', 'Áo kiểu nữ', 'Váy nữ', 'Quần jean nữ', 'Áo khoác nữ', 'Chân váy']::TEXT[]),
            ('KD-B', 'Trẻ em', 'Bé trai', 37,
             ARRAY['Áo thun bé trai', 'Quần short bé trai', 'Áo sơ mi bé trai', 'Set đồ bé trai', 'Quần jean bé trai', 'Áo khoác bé trai']::TEXT[]),
            ('KD-G', 'Trẻ em', 'Bé gái', 55,
             ARRAY['Váy bé gái', 'Áo kiểu bé gái', 'Set đồ bé gái', 'Quần legging bé gái', 'Áo khoác bé gái', 'Áo thun bé gái']::TEXT[])
    ) AS t(prefix, group_name, segment, start_no, name_bases)
), generated AS (
    SELECT
        format('%s-%03s', gd.prefix, gd.start_no + n - 1) AS id,
        gd.name_bases[((n - 1) % array_length(gd.name_bases, 1)) + 1] || ' ' || n AS name,
        gd.group_name,
        gd.segment,
        (ARRAY['S', 'M', 'L', 'XL'])[((n - 1) % 4) + 1] AS size,
        (ARRAY['Đen', 'Trắng', 'Xanh', 'Be', 'Nâu', 'Hồng'])[((n - 1) % 6) + 1] AS color,
        (179000 + ((n - 1) % 9) * 35000)::NUMERIC(14, 2) AS price
    FROM group_defs gd
    CROSS JOIN generate_series(1, 18) AS n
)
INSERT INTO shop_product (id, name, group_name, segment, size, color, price)
SELECT id, name, group_name, segment, size, color, price
FROM generated
WHERE NOT EXISTS (SELECT 1 FROM shop_product);
